---
language: python
install:
  - pip install coveralls
python:
  - "3.3"

# --source specifies what packages to cover, you probably want to use that option
script:
    coverage run --source={{ cookiecutter.project_name }} setup.py test

after_success: coveralls
